default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: ukirama

development:
  <<: *default
  database: clean_blog

test:
  <<: *default
  database: clean_blog_test

production:
  <<: *default
  database: clean_blog_production
